global:
  domain: mcdupyog-cicd.sparrowsoftech.in ## Add your Domain Name Eg: site.mydomain.com
  setup: fullsetup

cluster-configs:
  namespaces:
    create: true
    values: [jenkins, cert-manager]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"

jenkins:
  persistence:
    enabled: true
  #    aws:
  #      - volumeId: "vol-0e10a8959033657ff" # Add volume id for jenkins-home
  #        zone: ap-south-1b # Add respective availability_zones

  oauth:
    enabled: true
    acl:
      admin:
        - mcdupyog*mcdteam # Add github team. Members of this team gets admin access on jenkins
      user: # Add github team. Members of this team gets login access on jenkins
        - mcdupyog*mcdteam-ci
        - mcdupyog*mcdteam-qa
        - mcdupyog*mcdteam-uat

  jobBuilder: # Add jobBuilder repo's, add repo's ssh link
    repos: >-
      'https://github.com/mcd89/mcd_UPYOG.git','https://github.com/mcdupyog/mcd-UPYOG.git'
  deploymentJobs: # Setup deploymentJobs ACL
    - name: ci # deployment job name
      acl: [mcdupyog*mcdteam-ci] # GitHub team name, Members of the team get access to deployment job
    - name: qa
      acl: [mcdupyog*mcdteam-qa]
    - name: uat
      acl: [mcdupyog*mcdteam-uat]

  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    javaOpts: "-Xms2560M -Xmx2560M -Duser.timezone=Asia/Calcutta"

nginx-ingress:
  replicas: 1
  default-backend-service: "jenkins/jenkins"
  namespace: jenkins
  cert-issuer: "letsencrypt-staging"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"
  controller:
    image:
      repository: egovio/nginx-ingress-controller
      tag: "0.26.1"

cert-manager:
  namespace: jenkins
  clusterIssuer:
    stage:
      acme:
        email: "serveradmin@sparrowsoftech.com" # Add mail id

cluster-autoscaler:
  namespace: jenkins
  cloudProvider: aws
  awsRegion: ap-south-1
  autoDiscovery:
    clusterName: egov-cicd # Add cluster name
    tags:
      - kubernetes.io/cluster/egov-cicd # Add cluster name
